// Part of open-source library at https://github.com/klokantech/javascript
// compiled from https://github.com/klokantech/javascript/blob/master/src/osmnamesautocomplete.js
(function(){var g,aa=aa||{},n=this;function p(a){return void 0!==a}function ba(a,b){var c=a.split("."),d=n;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function da(){}
function ea(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==ea(a)}function fa(a){var b=ea(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function t(a){return"number"==typeof a}function ga(a){return"function"==ea(a)}function ha(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ia(a){return a[ja]||(a[ja]=++ka)}var ja="closure_uid_"+(1E9*Math.random()>>>0),ka=0;
function la(a,b,c){return a.call.apply(a.bind,arguments)}function ma(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return v.apply(null,arguments)}var w=Date.now||function(){return+new Date};
function x(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sc=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};var na;var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function pa(a){if(!qa.test(a))return a;-1!=a.indexOf("\x26")&&(a=a.replace(ra,"\x26amp;"));-1!=a.indexOf("\x3c")&&(a=a.replace(sa,"\x26lt;"));-1!=a.indexOf("\x3e")&&(a=a.replace(ta,"\x26gt;"));-1!=a.indexOf('"')&&(a=a.replace(ua,"\x26quot;"));-1!=a.indexOf("'")&&(a=a.replace(va,"\x26#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(wa,"\x26#0;"));return a}
var ra=/&/g,sa=/</g,ta=/>/g,ua=/"/g,va=/'/g,wa=/\x00/g,qa=/[\x00&<>"']/;function xa(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function ya(a,b){return a<b?-1:a>b?1:0};var za=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,
b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=r(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var l=h[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},Ba=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=r(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
function Ca(a){var b;a:{b=Da;for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:r(a)?a.charAt(b):a[b]}function Ea(a,b){var c=za(a,b),d;(d=0<=c)&&Array.prototype.splice.call(a,c,1);return d}function Fa(a){return Array.prototype.concat.apply(Array.prototype,arguments)}function Ga(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Ha(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Ia(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ja(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Ka(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function La(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ma(){var a=Na,b;for(b in a)return!1;return!0}var Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Pa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}function Qa(a){var b=arguments.length;if(1==b&&q(arguments[0]))return Qa.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};function Ra(a){if(a.L&&"function"==typeof a.L)return a.L();if(r(a))return a.split("");if(fa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ka(a)}
function Sa(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(fa(a)||r(a))y(a,b,c);else{var d;if(a.getKeys&&"function"==typeof a.getKeys)d=a.getKeys();else if(a.L&&"function"==typeof a.L)d=void 0;else if(fa(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=La(a);for(var e=Ra(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};function Ta(a,b){this.P={};this.h=[];this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)}g=Ta.prototype;g.yb=function(){return this.f};g.L=function(){Ua(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.P[this.h[b]]);return a};g.getKeys=function(){Ua(this);return this.h.concat()};g.qa=function(a){return Va(this.P,a)};
g.equals=function(a,b){if(this===a)return!0;if(this.f!=a.yb())return!1;var c=b||Wa;Ua(this);for(var d,e=0;d=this.h[e];e++)if(!c(this.get(d),a.get(d)))return!1;return!0};function Wa(a,b){return a===b}g.isEmpty=function(){return 0==this.f};g.clear=function(){this.P={};this.f=this.h.length=0};g.remove=function(a){return Va(this.P,a)?(delete this.P[a],this.f--,this.h.length>2*this.f&&Ua(this),!0):!1};
function Ua(a){if(a.f!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];Va(a.P,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.f!=a.h.length){for(var e={},c=b=0;b<a.h.length;)d=a.h[b],Va(e,d)||(a.h[c++]=d,e[d]=1),b++;a.h.length=c}}g.get=function(a,b){return Va(this.P,a)?this.P[a]:b};g.set=function(a,b){Va(this.P,a)||(this.f++,this.h.push(a));this.P[a]=b};g.addAll=function(a){var b;a instanceof Ta?(b=a.getKeys(),a=a.L()):(b=La(a),a=Ka(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};
g.forEach=function(a,b){for(var c=this.getKeys(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new Ta(this)};function Va(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Xa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function Ya(a,b){if(a)for(var c=a.split("\x26"),d=0;d<c.length;d++){var e=c[d].indexOf("\x3d"),f,h=null;0<=e?(f=c[d].substring(0,e),h=c[d].substring(e+1)):f=c[d];b(f,h?decodeURIComponent(h.replace(/\+/g," ")):"")}};function Za(a,b,c){this.f=this.m=null;this.G=a||null;this.zc=!!c}function z(a){a.m||(a.m=new Ta,a.f=0,a.G&&Ya(a.G,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}g=Za.prototype;g.yb=function(){z(this);return this.f};g.add=function(a,b){z(this);this.G=null;a=$a(this,a);var c=this.m.get(a);c||this.m.set(a,c=[]);c.push(b);this.f+=1;return this};g.remove=function(a){z(this);a=$a(this,a);return this.m.qa(a)?(this.G=null,this.f-=this.m.get(a).length,this.m.remove(a)):!1};
g.clear=function(){this.m=this.G=null;this.f=0};g.isEmpty=function(){z(this);return 0==this.f};g.qa=function(a){z(this);a=$a(this,a);return this.m.qa(a)};g.getKeys=function(){z(this);for(var a=this.m.L(),b=this.m.getKeys(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};g.L=function(a){z(this);var b=[];if(r(a))this.qa(a)&&(b=Fa(b,this.m.get($a(this,a))));else{a=this.m.L();for(var c=0;c<a.length;c++)b=Fa(b,a[c])}return b};
g.set=function(a,b){z(this);this.G=null;a=$a(this,a);this.qa(a)&&(this.f-=this.m.get(a).length);this.m.set(a,[b]);this.f+=1;return this};g.get=function(a,b){var c=a?this.L(a):[];return 0<c.length?String(c[0]):b};g.setValues=function(a,b){this.remove(a);0<b.length&&(this.G=null,this.m.set($a(this,a),Ga(b)),this.f+=b.length)};
g.toString=function(){if(this.G)return this.G;if(!this.m)return"";for(var a=[],b=this.m.getKeys(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.L(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="\x3d"+encodeURIComponent(String(d[f])));a.push(h)}return this.G=a.join("\x26")};g.clone=function(){var a=new Za;a.G=this.G;this.m&&(a.m=this.m.clone(),a.f=this.f);return a};function $a(a,b){var c=String(b);a.zc&&(c=c.toLowerCase());return c}
g.extend=function(a){for(var b=0;b<arguments.length;b++)Sa(arguments[b],function(a,b){this.add(b,a)},this)};var ab;a:{var bb=n.navigator;if(bb){var cb=bb.userAgent;if(cb){ab=cb;break a}}ab=""}function A(a){return-1!=ab.indexOf(a)};function db(a){db[" "](a);return a}db[" "]=da;function eb(a,b){try{return db(a[b]),!0}catch(c){}return!1}function fb(a,b){var c=gb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var hb=A("Opera"),B=A("Trident")||A("MSIE"),D=A("Edge"),ib=D||B,E=A("Gecko")&&!(-1!=ab.toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),G=-1!=ab.toLowerCase().indexOf("webkit")&&!A("Edge"),H=A("Macintosh");function jb(){var a=n.document;return a?a.documentMode:void 0}var kb;
a:{var lb="",mb=function(){var a=ab;if(E)return/rv\:([^\);]+)(\)|;)/.exec(a);if(D)return/Edge\/([\d\.]+)/.exec(a);if(B)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(G)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();mb&&(lb=mb?mb[1]:"");if(B){var nb=jb();if(null!=nb&&nb>parseFloat(lb)){kb=String(nb);break a}}kb=lb}var gb={};
function I(a){return fb(a,function(){for(var b=0,c=oa(String(kb)).split("."),d=oa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=ya(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||ya(0==h[2].length,0==k[2].length)||ya(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}
var ob=n.document,J=ob&&B?jb()||("CSS1Compat"==ob.compatMode?parseInt(kb,10):5):void 0;var pb=!B||9<=Number(J);!E&&!B||B&&9<=Number(J)||E&&I("1.9.1");B&&I("9");function K(a,b){this.x=p(a)?a:0;this.y=p(b)?b:0}g=K.prototype;g.clone=function(){return new K(this.x,this.y)};g.equals=function(a){return a instanceof K&&(this==a?!0:this&&a?this.x==a.x&&this.y==a.y:!1)};function qb(a,b){return new K(a.x-b.x,a.y-b.y)}g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.translate=function(a,b){a instanceof K?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),t(b)&&(this.y+=b));return this};g.scale=function(a,b){var c=t(b)?b:a;this.x*=a;this.y*=c;return this};function rb(a,b){this.width=a;this.height=b}g=rb.prototype;g.clone=function(){return new rb(this.width,this.height)};g.lc=function(){return this.width*this.height};g.isEmpty=function(){return!this.lc()};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.scale=function(a,b){var c=t(b)?b:a;this.width*=a;this.height*=c;return this};function L(a){return a?new sb(M(a)):na||(na=new sb)}function tb(a,b){Ia(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:ub.hasOwnProperty(d)?a.setAttribute(ub[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}
var ub={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function vb(a){var b=wb(a);a=xb(a);return B&&I("10")&&a.pageYOffset!=b.scrollTop?new K(b.scrollLeft,b.scrollTop):new K(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)}
function wb(a){return a.scrollingElement?a.scrollingElement:!G&&yb(a)?a.documentElement:a.body||a.documentElement}function xb(a){return a.parentWindow||a.defaultView}function zb(a,b,c,d){function e(c){c&&b.appendChild(r(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!fa(f)||ha(f)&&0<f.nodeType?e(f):y(Ab(f)?Ga(f):f,e)}}function yb(a){return"CSS1Compat"==a.compatMode}function Bb(a){for(var b;b=a.firstChild;)a.removeChild(b)}
function M(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ab(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==typeof a.item||"string"==typeof a.item;if(ga(a))return"function"==typeof a.item}return!1}function Cb(a){return Db(a,function(a){return"FORM"==a.nodeName&&!0})}function Db(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null}function sb(a){this.v=a||n.document||document}g=sb.prototype;
g.getElement=function(a){return r(a)?this.v.getElementById(a):a};g.getElementsByTagName=function(a,b){return(b||this.v).getElementsByTagName(String(a))};g.setProperties=tb;
g.xb=function(a,b,c){var d=this.v,e=arguments,f=String(e[0]),h=e[1];if(!pb&&h&&(h.name||h.type)){f=["\x3c",f];h.name&&f.push(' name\x3d"',pa(h.name),'"');if(h.type){f.push(' type\x3d"',pa(h.type),'"');var k={};Pa(k,h);delete k.type;h=k}f.push("\x3e");f=f.join("")}f=d.createElement(f);h&&(r(h)?f.className=h:q(h)?f.className=h.join(" "):tb(f,h));2<e.length&&zb(d,f,e,2);return f};g.createElement=function(a){return this.v.createElement(String(a))};g.createTextNode=function(a){return this.v.createTextNode(String(a))};
g.appendChild=function(a,b){a.appendChild(b)};g.append=function(a,b){zb(M(a),a,arguments,1)};g.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Ic=Bb;g.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};g.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Eb(a){if(a.classList)return a.classList;a=a.className;return r(a)&&a.match(/\S+/g)||[]}function Fb(a,b){var c;a.classList?c=a.classList.contains(b):(c=Eb(a),c=0<=za(c,b));return c}function Gb(a,b){a.classList?a.classList.add(b):Fb(a,b)||(a.className+=0<a.className.length?" "+b:b)}function Hb(a,b){if(a.classList)y(b,function(b){Gb(a,b)});else{var c={};y(Eb(a),function(a){c[a]=!0});y(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function Ib(a,b){a.classList?a.classList.remove(b):Fb(a,b)&&(a.className=Aa(Eb(a),function(a){return a!=b}).join(" "))}function Jb(a,b){a.classList?y(b,function(b){Ib(a,b)}):a.className=Aa(Eb(a),function(a){return!(0<=za(b,a))}).join(" ")};function N(){0!=Kb&&(Lb[ia(this)]=this);this.ra=this.ra;this.Ja=this.Ja}var Kb=0,Lb={};N.prototype.ra=!1;N.prototype.W=function(){if(!this.ra&&(this.ra=!0,this.l(),0!=Kb)){var a=ia(this);delete Lb[a]}};N.prototype.l=function(){if(this.Ja)for(;this.Ja.length;)this.Ja.shift()()};function Mb(a){a&&"function"==typeof a.W&&a.W()};var Nb=!B||9<=Number(J),Ob=B&&!I("9");!G||I("528");E&&I("1.9b")||B&&I("8")||hb&&I("9.5")||G&&I("528");E&&!I("8")||B&&I("9");function O(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.fa=!1;this.Yb=!0}O.prototype.stopPropagation=function(){this.fa=!0};O.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Yb=!1};function P(a,b){O.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.ja=this.state=null;if(a){var c=this.type=a.type,d=a.changedTouches?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?E&&(eb(e,"nodeName")||(e=null)):"mouseover"==c?e=a.fromElement:
"mouseout"==c&&(e=a.toElement);this.relatedTarget=e;null===d?(this.offsetX=G||void 0!==a.offsetX?a.offsetX:a.layerX,this.offsetY=G||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0):(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0);this.button=a.button;this.keyCode=
a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.ja=a;a.defaultPrevented&&this.preventDefault()}}x(P,O);P.prototype.stopPropagation=function(){P.o.stopPropagation.call(this);this.ja.stopPropagation?this.ja.stopPropagation():this.ja.cancelBubble=!0};
P.prototype.preventDefault=function(){P.o.preventDefault.call(this);var a=this.ja;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ob)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Pb="closure_listenable_"+(1E6*Math.random()|0);function Qb(a){return!(!a||!a[Pb])}var Rb=0;function Tb(a,b,c,d,e){this.listener=a;this.La=null;this.src=b;this.type=c;this.pa=!!d;this.Aa=e;this.key=++Rb;this.na=this.za=!1}function Ub(a){a.na=!0;a.listener=null;a.La=null;a.src=null;a.Aa=null};function Vb(a){this.src=a;this.A={};this.xa=0}g=Vb.prototype;g.add=function(a,b,c,d,e){var f=a.toString();a=this.A[f];a||(a=this.A[f]=[],this.xa++);var h=Wb(a,b,d,e);-1<h?(b=a[h],c||(b.za=!1)):(b=new Tb(b,this.src,f,!!d,e),b.za=c,a.push(b));return b};g.remove=function(a,b,c,d){a=a.toString();if(!(a in this.A))return!1;var e=this.A[a];b=Wb(e,b,c,d);return-1<b?(Ub(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.A[a],this.xa--),!0):!1};
function Xb(a,b){var c=b.type;c in a.A&&Ea(a.A[c],b)&&(Ub(b),0==a.A[c].length&&(delete a.A[c],a.xa--))}g.Ma=function(a){a=a&&a.toString();var b=0,c;for(c in this.A)if(!a||c==a){for(var d=this.A[c],e=0;e<d.length;e++)++b,Ub(d[e]);delete this.A[c];this.xa--}return b};g.sa=function(a,b,c,d){a=this.A[a.toString()];var e=-1;a&&(e=Wb(a,b,c,d));return-1<e?a[e]:null};
g.hasListener=function(a,b){var c=p(a),d=c?a.toString():"",e=p(b);return Ja(this.A,function(a){for(var h=0;h<a.length;++h)if(!(c&&a[h].type!=d||e&&a[h].pa!=b))return!0;return!1})};function Wb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.na&&f.listener==b&&f.pa==!!c&&f.Aa==d)return e}return-1};var Yb="closure_lm_"+(1E6*Math.random()|0),Zb={},$b=0;function R(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)R(a,b[f],c,d,e);return null}c=ac(c);return Qb(a)?a.D(b,c,d,e):bc(a,b,c,!1,d,e)}
function bc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=cc(a);k||(a[Yb]=k=new Vb(a));c=k.add(b,c,d,e,f);if(c.La)return c;d=dc();c.La=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,h);else if(a.attachEvent)a.attachEvent(ec(b.toString()),d);else throw Error("addEventListener and attachEvent are unavailable.");$b++;return c}
function dc(){var a=fc,b=Nb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function gc(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)gc(a,b[f],c,d,e);return null}c=ac(c);return Qb(a)?a.kb(b,c,d,e):bc(a,b,c,!0,d,e)}function hc(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)hc(a,b[f],c,d,e);else c=ac(c),Qb(a)?a.F(b,c,d,e):a&&(a=cc(a))&&(b=a.sa(b,c,!!d,e))&&S(b)}
function S(a){if(t(a)||!a||a.na)return;var b=a.src;if(Qb(b)){Xb(b.O,a);return}var c=a.type,d=a.La;b.removeEventListener?b.removeEventListener(c,d,a.pa):b.detachEvent&&b.detachEvent(ec(c),d);$b--;(c=cc(b))?(Xb(c,a),0==c.xa&&(c.src=null,b[Yb]=null)):Ub(a)}function ec(a){return a in Zb?Zb[a]:Zb[a]="on"+a}function ic(a,b,c,d){var e=!0;if(a=cc(a))if(b=a.A[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.pa==c&&!f.na&&(f=jc(f,d),e=e&&!1!==f)}return e}
function jc(a,b){var c=a.listener,d=a.Aa||a.src;a.za&&S(a);return c.call(d,b)}
function fc(a,b){if(a.na)return!0;if(!Nb){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new P(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(l){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,h=e.length-1;!c.fa&&0<=h;h--){c.currentTarget=e[h];var k=ic(e[h],f,!0,c),d=d&&k}for(h=0;!c.fa&&h<
e.length;h++)c.currentTarget=e[h],k=ic(e[h],f,!1,c),d=d&&k}return d}return jc(a,new P(b,this))}function cc(a){a=a[Yb];return a instanceof Vb?a:null}var kc="__closure_events_fn_"+(1E9*Math.random()>>>0);function ac(a){if(ga(a))return a;a[kc]||(a[kc]=function(b){return a.handleEvent(b)});return a[kc]};function T(){N.call(this);this.O=new Vb(this);this.jc=this;this.nb=null}x(T,N);T.prototype[Pb]=!0;g=T.prototype;g.addEventListener=function(a,b,c,d){R(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){hc(this,a,b,c,d)};
g.dispatchEvent=function(a){var b,c=this.nb;if(c)for(b=[];c;c=c.nb)b.push(c);var c=this.jc,d=a.type||a;if(r(a))a=new O(a,c);else if(a instanceof O)a.target=a.target||c;else{var e=a;a=new O(d,c);Pa(a,e)}var e=!0,f;if(b)for(var h=b.length-1;!a.fa&&0<=h;h--)f=a.currentTarget=b[h],e=lc(f,d,!0,a)&&e;a.fa||(f=a.currentTarget=c,e=lc(f,d,!0,a)&&e,a.fa||(e=lc(f,d,!1,a)&&e));if(b)for(h=0;!a.fa&&h<b.length;h++)f=a.currentTarget=b[h],e=lc(f,d,!1,a)&&e;return e};
g.l=function(){T.o.l.call(this);this.O&&this.O.Ma(void 0);this.nb=null};g.D=function(a,b,c,d){return this.O.add(String(a),b,!1,c,d)};g.kb=function(a,b,c,d){return this.O.add(String(a),b,!0,c,d)};g.F=function(a,b,c,d){return this.O.remove(String(a),b,c,d)};function lc(a,b,c,d){b=a.O.A[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.na&&h.pa==c){var k=h.listener,l=h.Aa||h.src;h.za&&Xb(a.O,h);e=!1!==k.call(l,d)&&e}}return e&&0!=d.Yb}
g.sa=function(a,b,c,d){return this.O.sa(String(a),b,c,d)};g.hasListener=function(a,b){return this.O.hasListener(p(a)?String(a):void 0,b)};function mc(a,b){T.call(this);this.ea=a||1;this.oa=b||n;this.Xa=v(this.Oc,this);this.jb=w()}x(mc,T);g=mc.prototype;g.enabled=!1;g.g=null;g.setInterval=function(a){this.ea=a;this.g&&this.enabled?(this.stop(),this.start()):this.g&&this.stop()};
g.Oc=function(){if(this.enabled){var a=w()-this.jb;0<a&&a<.8*this.ea?this.g=this.oa.setTimeout(this.Xa,this.ea-a):(this.g&&(this.oa.clearTimeout(this.g),this.g=null),this.dispatchEvent("tick"),this.enabled&&(this.g=this.oa.setTimeout(this.Xa,this.ea),this.jb=w()))}};g.start=function(){this.enabled=!0;this.g||(this.g=this.oa.setTimeout(this.Xa,this.ea),this.jb=w())};g.stop=function(){this.enabled=!1;this.g&&(this.oa.clearTimeout(this.g),this.g=null)};g.l=function(){mc.o.l.call(this);this.stop();delete this.oa};
function nc(a,b,c){if(ga(a))c&&(a=v(a,c));else if(a&&"function"==typeof a.handleEvent)a=v(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:n.setTimeout(a,b||0)};function oc(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function pc(){}pc.prototype.wb=null;function qc(a){var b;(b=a.wb)||(b={},rc(a)&&(b[0]=!0,b[1]=!0),b=a.wb=b);return b};var sc;function tc(){}x(tc,pc);function uc(a){return(a=rc(a))?new ActiveXObject(a):new XMLHttpRequest}function rc(a){if(!a.Db&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Db=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Db}sc=new tc;function vc(a){T.call(this);this.headers=new Ta;this.Ua=a||null;this.V=!1;this.Ta=this.a=null;this.Ga=this.hb="";this.ca=this.bb=this.Da=this.Za=!1;this.Qa=0;this.Pa=null;this.Xb=wc;this.sb=this.Gc=this.hc=!1}x(vc,T);var wc="",xc=/^https?$/i,yc=["POST","PUT"],zc=[];function Ac(a,b){var c=new vc;zc.push(c);b&&c.D("complete",b);c.kb("ready",c.pc);c.send(a,void 0,void 0,void 0);return c}g=vc.prototype;g.pc=function(){this.W();Ea(zc,this)};
g.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request\x3d"+this.hb+"; newUri\x3d"+a);b=b?b.toUpperCase():"GET";this.hb=a;this.Ga="";this.Za=!1;this.V=!0;this.a=this.Ua?uc(this.Ua):uc(sc);this.Ta=this.Ua?qc(this.Ua):qc(sc);this.a.onreadystatechange=v(this.Tb,this);this.Gc&&"onprogress"in this.a&&(this.a.onprogress=v(function(a){this.Sb(a,!0)},this),this.a.upload&&(this.a.upload.onprogress=v(this.Sb,this)));try{this.bb=!0,this.a.open(b,String(a),!0),
this.bb=!1}catch(f){Bc(this,f);return}a=c||"";var e=this.headers.clone();d&&Sa(d,function(a,b){e.set(b,a)});d=Ca(e.getKeys());c=n.FormData&&a instanceof n.FormData;!(0<=za(yc,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset\x3dutf-8");e.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Xb&&(this.a.responseType=this.Xb);"withCredentials"in this.a&&this.a.withCredentials!==this.hc&&(this.a.withCredentials=this.hc);try{Cc(this),0<this.Qa&&((this.sb=Dc(this.a))?
(this.a.timeout=this.Qa,this.a.ontimeout=v(this.ac,this)):this.Pa=nc(this.ac,this.Qa,this)),this.Da=!0,this.a.send(a),this.Da=!1}catch(f){Bc(this,f)}};function Dc(a){return B&&I(9)&&t(a.timeout)&&p(a.ontimeout)}function Da(a){return"content-type"==a.toLowerCase()}g.ac=function(){"undefined"!=typeof aa&&this.a&&(this.Ga="Timed out after "+this.Qa+"ms, aborting",this.dispatchEvent("timeout"),this.abort(8))};function Bc(a,b){a.V=!1;a.a&&(a.ca=!0,a.a.abort(),a.ca=!1);a.Ga=b;Ec(a);Fc(a)}
function Ec(a){a.Za||(a.Za=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}g.abort=function(){this.a&&this.V&&(this.V=!1,this.ca=!0,this.a.abort(),this.ca=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Fc(this))};g.l=function(){this.a&&(this.V&&(this.V=!1,this.ca=!0,this.a.abort(),this.ca=!1),Fc(this,!0));vc.o.l.call(this)};g.Tb=function(){this.ra||(this.bb||this.Da||this.ca?Gc(this):this.Dc())};g.Dc=function(){Gc(this)};
function Gc(a){if(a.V&&"undefined"!=typeof aa&&(!a.Ta[1]||4!=Hc(a)||2!=a.getStatus()))if(a.Da&&4==Hc(a))nc(a.Tb,0,a);else if(a.dispatchEvent("readystatechange"),4==Hc(a)){a.V=!1;try{if(Ic(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{var b;try{b=2<Hc(a)?a.a.statusText:""}catch(c){b=""}a.Ga=b+" ["+a.getStatus()+"]";Ec(a)}}finally{Fc(a)}}}g.Sb=function(a,b){this.dispatchEvent(Jc(a,"progress"));this.dispatchEvent(Jc(a,b?"downloadprogress":"uploadprogress"))};
function Jc(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}}function Fc(a,b){if(a.a){Cc(a);var c=a.a,d=a.Ta[0]?da:null;a.a=null;a.Ta=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}}function Cc(a){a.a&&a.sb&&(a.a.ontimeout=null);t(a.Pa)&&(n.clearTimeout(a.Pa),a.Pa=null)}g.eb=function(){return!!this.a};
function Ic(a){var b=a.getStatus(),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.hb).match(Xa)[1]||null,!a&&n.self&&n.self.location&&(a=n.self.location.protocol,a=a.substr(0,a.length-1)),b=!xc.test(a?a.toLowerCase():"");c=b}return c}function Hc(a){return a.a?a.a.readyState:0}g.getStatus=function(){try{return 2<Hc(this)?this.a.status:-1}catch(a){return-1}};
g.getResponseHeader=function(a){if(this.a&&4==Hc(this))return a=this.a.getResponseHeader(a),null===a?void 0:a};g.getAllResponseHeaders=function(){return this.a&&4==Hc(this)?this.a.getAllResponseHeaders():""};function Kc(a,b,c){T.call(this);this.Z=a;this.Oa=c;this.I=b;R(b,[Lc,Mc,Nc,Oc],this.handleEvent,!1,this);this.K=null;this.j=[];this.X=-1;this.B=0;this.ba=this.w=null;this.Fb={}}x(Kc,T);g=Kc.prototype;g.Cc=10;g.mc=!0;g.vb=!1;g.ic=!1;g.bc=!1;var Lc="hilite",Mc="select",Oc="dismiss",Nc="canceldismiss";g=Kc.prototype;
g.handleEvent=function(a){var b=this.Z;if(a.target==this.I)switch(a.type){case Lc:this.T(a.row);break;case Mc:var c=!1;if(t(a.row)){a=a.row;var d=this.j[Pc(this,a)],c=!!d&&b.fb&&b.fb(d);d&&!c&&this.X!=a&&this.T(a)}c||Qc(this);break;case Nc:Rc(this);break;case Oc:Sc(this)}};g.getTarget=function(){return this.w};g.setTarget=function(a){this.w=a};
function Tc(a){for(var b=a.B+a.j.length-1,c=a.X,d=0;d<a.j.length;d++){if(c>=a.B&&c<b)c++;else if(-1==c)c=a.B;else if(a.vb&&c==b){a.T(-1);break}else if(a.ic&&c==b)c=a.B;else break;if(a.T(c))break}}function Uc(a){for(var b=a.B+a.j.length-1,c=a.X,d=0;d<a.j.length;d++){if(c>a.B)c--;else if(a.vb&&c==a.B){a.T(-1);break}else if(!a.ic||-1!=c&&c!=a.B)break;else c=b;if(a.T(c))break}}g.T=function(a){var b=Pc(this,a),c=this.j[b];return c&&this.Z.fb&&this.Z.fb(c)?!1:(this.X=a,this.I.T(a),-1!=b)};
function Qc(a){var b=Pc(a,a.X);if(-1!=b){var c=a.j[b],d=a.Oa;if(d.c){var e=c.toString();if(p(void 0)?0:d.ma){var f=Vc(d,d.c.value,Wc(d.c)[0]),h=Xc(d,d.c.value);d.Lc.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.qc);d.Rc&&(0==f||/^[\s\xa0]*$/.test(h[f-1])||(e=" "+e),f==h.length-1&&(e+=" "));if(e!=h[f]){h[f]=e;e=d.c;(E||B&&I("9"))&&e.blur();e.value=h.join("");for(var k=0,l=0;l<=f;l++)k+=h[l].length;e.focus();f=k;h=d.c;e=f;Yc(h)?h.selectionStart=e:B&&!I("9")&&(k=Zc(h),l=k[0],l.inRange(k[1])&&(e=$c(h,e),l.collapse(!0),
l.move("character",e),l.select()));h=d.c;Yc(h)?h.selectionEnd=f:B&&!I("9")&&(k=Zc(h),e=k[1],k[0].inRange(e)&&(f=$c(h,f),h=$c(h,Wc(h)[0]),e.collapse(!0),e.moveEnd("character",f-h),e.select()))}}else d.c.value=e;d.rb=!0}a.bc?(a.K=null,Sc(a)):a.S();a.dispatchEvent({type:"update",row:c,index:b});a.bc&&a.Oa.update(!0);return!0}a.S();a.dispatchEvent({type:"update",row:null,index:null});return!1}
g.S=function(){this.X=-1;this.K=null;this.B+=this.j.length;this.j=[];window.clearTimeout(this.ba);this.ba=null;this.I.S();this.dispatchEvent("suggestionsupdate");this.dispatchEvent(Oc)};function Sc(a){a.ba||(a.ba=window.setTimeout(v(a.S,a),100))}g.Eb=function(){return this.ba?(window.clearTimeout(this.ba),this.ba=null,!0):!1};function Rc(a){a.Eb()||window.setTimeout(v(a.Eb,a),10)}g.l=function(){Kc.o.l.call(this);delete this.Fb;this.I.W();this.Oa.W();this.Z=null};
g.Ac=function(a,b,c){this.K==a&&this.pb(b,c)};g.pb=function(a,b){var c="object"==ea(b)&&b,d=(c?c.Tc():b)?Pc(this,this.X):-1;this.B+=this.j.length;this.j=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.B+f,data:a[f]});f=null;this.w&&(f=this.Fb[ia(this.w)]||this.w);this.I.kc=f;this.I.pb(e,this.K,this.w);f=this.mc;c&&void 0!==c.uc()&&(f=c.uc());this.X=-1;(f||0<=d)&&0!=e.length&&this.K&&(0<=d?this.T(this.B+d):Tc(this));this.dispatchEvent("suggestionsupdate")};
function Pc(a,b){var c=b-a.B;return 0>c||c>=a.j.length?-1:c}g.update=function(a){this.Oa.update(a)};var ad;Qa("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));function bd(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}
function cd(a,b,c){q(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(ad||(ad={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=ad,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}function dd(a,b){var c="";b&&(c=b.id);cd(a,"activedescendant",c)};function Wc(a){var b=0,c=0;if(Yc(a))b=a.selectionStart,c=-1;else if(B&&!I("9")){var d=Zc(a),e=d[0],d=d[1];if(e.inRange(d)){e.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=e.text;for(c=!1;!c;)0==e.compareEndPoints("StartToEnd",e)?c=!0:(e.moveEnd("character",-1),e.text==a?b+="\r\n":c=!0);e=[b.length,-1];return e}b=e.text.length;c=-1}}return[b,c]}
function Zc(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function $c(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function Yc(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};function ed(a){N.call(this);this.ka=a;this.h={}}x(ed,N);var fd=[];g=ed.prototype;g.D=function(a,b,c,d){q(b)||(b&&(fd[0]=b.toString()),b=fd);for(var e=0;e<b.length;e++){var f=R(a,b[e],c||this.handleEvent,d||!1,this.ka||this);if(!f)break;this.h[f.key]=f}return this};g.kb=function(a,b,c,d){return gd(this,a,b,c,d)};function gd(a,b,c,d,e,f){if(q(c))for(var h=0;h<c.length;h++)gd(a,b,c[h],d,e,f);else{b=gc(b,c,d||a.handleEvent,e,f||a.ka||a);if(!b)return a;a.h[b.key]=b}return a}
g.F=function(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)this.F(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.ka||this,c=ac(c),d=!!d,b=Qb(a)?a.sa(b,c,d,e):a?(a=cc(a))?a.sa(b,c,d,e):null:null,b&&(S(b),delete this.h[b.key]);return this};g.Ma=function(){Ia(this.h,function(a,b){this.h.hasOwnProperty(b)&&S(a)},this);this.h={}};g.l=function(){ed.o.l.call(this);this.Ma()};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function hd(a,b,c,d,e,f){if(!(B||D||G&&I("525")))return!0;if(H&&e)return id(a);if(e&&!d)return!1;t(b)&&(b=jd(b));e=17==b||18==b||H&&91==b;if((!c||H)&&e||H&&16==b&&(d||f))return!1;if((G||D)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(B&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!(G||D)}return id(a)}
function id(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||(G||D)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function jd(a){if(E)a=kd(a);else if(H&&G)a:switch(a){case 93:a=91;break a}return a}
function kd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function ld(a,b){T.call(this);a&&md(this,a,b)}x(ld,T);g=ld.prototype;g.b=null;g.Ea=null;g.gb=null;g.Fa=null;g.C=-1;g.Y=-1;g.Wa=!1;
var nd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},od={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},pd=B||D||G&&I("525"),qd=H&&E;g=ld.prototype;
g.vc=function(a){if(G||D)if(17==this.C&&!a.ctrlKey||18==this.C&&!a.altKey||H&&91==this.C&&!a.metaKey)this.Y=this.C=-1;-1==this.C&&(a.ctrlKey&&17!=a.keyCode?this.C=17:a.altKey&&18!=a.keyCode?this.C=18:a.metaKey&&91!=a.keyCode&&(this.C=91));pd&&!hd(a.keyCode,this.C,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.Y=jd(a.keyCode),qd&&(this.Wa=a.altKey))};g.xc=function(a){this.Y=this.C=-1;this.Wa=a.altKey};
g.handleEvent=function(a){var b=a.ja,c,d,e=b.altKey;B&&"keypress"==a.type?(c=this.Y,d=13!=c&&27!=c?b.keyCode:0):(G||D)&&"keypress"==a.type?(c=this.Y,d=0<=b.charCode&&63232>b.charCode&&id(c)?b.charCode:0):hb&&!G?(c=this.Y,d=id(c)?b.keyCode:0):(c=b.keyCode||this.Y,d=b.charCode||0,qd&&(e=this.Wa),H&&63==d&&224==c&&(c=191));var f=c=jd(c);c?63232<=c&&c in nd?f=nd[c]:25==c&&a.shiftKey&&(f=9):b.keyIdentifier&&b.keyIdentifier in od&&(f=od[b.keyIdentifier]);a=f==this.C;this.C=f;b=new rd(f,d,a,b);b.altKey=
e;this.dispatchEvent(b)};g.getElement=function(){return this.b};function md(a,b,c){a.Fa&&a.detach();a.b=b;a.Ea=R(a.b,"keypress",a,c);a.gb=R(a.b,"keydown",a.vc,c,a);a.Fa=R(a.b,"keyup",a.xc,c,a)}g.detach=function(){this.Ea&&(S(this.Ea),S(this.gb),S(this.Fa),this.Fa=this.gb=this.Ea=null);this.b=null;this.Y=this.C=-1};g.l=function(){ld.o.l.call(this);this.detach()};function rd(a,b,c,d){P.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}x(rd,P);var sd=A("iPhone")&&!A("iPod")&&!A("iPad")||A("iPod"),td=A("iPad");function ud(a,b,c,d){N.call(this);d=d||150;this.ma=null!=c?c:!0;this.va=a||",;";this.qc=this.va.substring(0,1);a=this.ma?"[\\s"+this.va+"]+":"[\\s]+";this.cc=new RegExp("^"+a+"|"+a+"$","g");this.Lc=new RegExp("\\s*["+this.va+"]$");this.Jb=b||"";this.Fc=!1;this.Ec=this.ma;this.g=0<d?new mc(d):null;this.s=new ed(this);this.ya=new ed(this);this.ua=new ld;this.Hb=-1}x(ud,N);var vd=(sd||td)&&!I("533.17.9");g=ud.prototype;g.Rc=!0;g.tc=!0;g.ec=!1;g.Nc=!0;g.Mc=!0;g.Va=null;g.c=null;g.ib="";g.aa=!1;g.rb=!1;
g.dc=!0;g.l=function(){ud.o.l.call(this);null!=this.Va&&window.clearTimeout(this.Va);this.s.W();delete this.s;this.ya.W();this.ua.W();Mb(this.g)};function wd(a){a.g?a.g.setInterval(300):a.g=new mc(300)}
function xd(a,b){switch(b.keyCode){case 40:if(a.i.I.R){a.ec?Uc(a.i):Tc(a.i);b.preventDefault();return}if(!a.ma){a.update(!0);b.preventDefault();return}break;case 38:if(a.i.I.R){a.ec?Tc(a.i):Uc(a.i);b.preventDefault();return}break;case 9:if(!a.i.I.R||b.shiftKey||a.Fc)a.i.S();else if(a.update(),Qc(a.i)&&a.Ec){b.preventDefault();return}break;case 13:if(a.i.I.R){if(a.update(),Qc(a.i)){b.preventDefault();b.stopPropagation();return}}else a.i.S();break;case 27:if(a.i.I.R){a.i.S();b.preventDefault();b.stopPropagation();
return}break;case 229:if(!a.aa){a.aa||(a.s.D(a.c,"keyup",a.Pb),a.s.D(a.c,"keypress",a.Ob),a.aa=!0);return}break;default:a.g&&!a.dc&&(a.g.stop(),a.g.start())}yd(a,b)}function yd(a,b){var c=a.ma&&b.charCode&&-1!=a.va.indexOf(String.fromCharCode(b.charCode));a.Nc&&c&&a.update();a.Mc&&c&&Qc(a.i)&&b.preventDefault()}g.wc=function(){return!1};g.ab=function(a){zd(this,a.target||null)};
function zd(a,b){a.ya.Ma();a.i&&Rc(a.i);b!=a.c&&(a.c=b,a.g&&(a.g.start(),a.s.D(a.g,"tick",a.Ub)),a.ib=a.c.value,md(a.ua,a.c),a.s.D(a.ua,"key",a.Qb),a.s.D(a.c,"mousedown",a.Rb),B&&a.s.D(a.c,"keypress",a.Mb))}g.$a=function(){vd?this.Va=window.setTimeout(v(this.Vb,this),0):this.Vb()};
g.Vb=function(){this.c&&(this.s.F(this.ua,"key",this.Qb),this.ua.detach(),this.s.F(this.c,"keyup",this.wc),this.s.F(this.c,"mousedown",this.Rb),B&&this.s.F(this.c,"keypress",this.Mb),this.aa&&Ad(this),this.c=null,this.g&&(this.g.stop(),this.s.F(this.g,"tick",this.Ub)),this.i&&Sc(this.i))};g.Ub=function(){this.update()};g.Nb=function(a){this.ab(a)};g.Qb=function(a){this.Hb=a.keyCode;this.i&&xd(this,a)};g.Ob=function(){this.aa&&229!=this.Hb&&Ad(this)};
g.Pb=function(a){this.aa&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&Ad(this)};g.Rb=function(){};function Ad(a){a.aa&&(a.aa=!1,a.s.F(a.c,"keypress",a.Ob),a.s.F(a.c,"keyup",a.Pb))}g.Mb=function(a){yd(this,a)};
g.update=function(a){if(this.c&&(a||this.c.value!=this.ib)){if(a||!this.rb){a=Wc(this.c)[0];var b=this.c.value;a=Xc(this,b)[Vc(this,b,a)];a=this.cc?String(a).replace(this.cc,""):a;this.i&&(this.i.setTarget(this.c),b=this.i,b.K!=a&&(b.K=a,Bd(b.Z,b.K,b.Cc,v(b.Ac,b)),Rc(b)))}this.ib=this.c.value}this.rb=!1};function Vc(a,b,c){a=Xc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}
function Xc(a,b){if(!a.ma)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,h=!1;f<c.length;f++)a.Jb&&-1!=a.Jb.indexOf(c[f])?(a.tc&&!h&&(d.push(e.join("")),e.length=0),e.push(c[f]),h=!h):h||-1==a.va.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function Cd(){T.call(this);this.J=Dd;this.endTime=this.startTime=null}x(Cd,T);var Dd=0;Cd.prototype.U=function(){this.M("begin")};Cd.prototype.$=function(){this.M("end")};Cd.prototype.M=function(a){this.dispatchEvent(a)};function Ed(a,b,c){N.call(this);this.lb=a;this.ea=b||0;this.ka=c;this.oc=v(this.rc,this)}x(Ed,N);g=Ed.prototype;g.ta=0;g.l=function(){Ed.o.l.call(this);this.stop();delete this.lb;delete this.ka};g.start=function(a){this.stop();this.ta=nc(this.oc,p(a)?a:this.ea)};g.stop=function(){this.eb()&&n.clearTimeout(this.ta);this.ta=0};g.eb=function(){return 0!=this.ta};g.rc=function(){this.ta=0;this.lb&&this.lb.call(this.ka)};var Na={},Fd=null;function Gd(a){a=ia(a);delete Na[a];Ma()&&Fd&&Fd.stop()}function Hd(){Fd||(Fd=new Ed(function(){Id()},20));var a=Fd;a.eb()||a.start()}function Id(){var a=w();Ia(Na,function(b){Jd(b,a)});Ma()||Hd()};function Kd(a,b,c,d){Cd.call(this);if(!q(a)||!q(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.wa=a;this.sc=b;this.duration=c;this.tb=d;this.coords=[];this.H=0}x(Kd,Cd);g=Kd.prototype;
g.play=function(a){if(a||this.J==Dd)this.H=0,this.coords=this.wa;else if(1==this.J)return!1;Gd(this);this.startTime=a=w();-1==this.J&&(this.startTime-=this.duration*this.H);this.endTime=this.startTime+this.duration;this.H||this.U();this.M("play");-1==this.J&&this.M("resume");this.J=1;var b=ia(this);b in Na||(Na[b]=this);Hd();Jd(this,a);return!0};g.stop=function(a){Gd(this);this.J=Dd;a&&(this.H=1);Ld(this,this.H);this.M("stop");this.$()};g.pause=function(){1==this.J&&(Gd(this),this.J=-1,this.M("pause"))};
g.l=function(){this.J==Dd||this.stop(!1);this.M("destroy");Kd.o.l.call(this)};function Jd(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);a.H=(b-a.startTime)/(a.endTime-a.startTime);1<a.H&&(a.H=1);Ld(a,a.H);1==a.H?(a.J=Dd,Gd(a),a.M("finish"),a.$()):1==a.J&&a.mb()}function Ld(a,b){ga(a.tb)&&(b=a.tb(b));a.coords=Array(a.wa.length);for(var c=0;c<a.wa.length;c++)a.coords[c]=(a.sc[c]-a.wa[c])*b+a.wa[c]}g.mb=function(){this.M("animate")};
g.M=function(a){this.dispatchEvent(new Md(a,this))};function Md(a,b){O.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.H=b.H;this.state=b.J}x(Md,O);function U(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}g=U.prototype;g.getWidth=function(){return this.right-this.left};g.getHeight=function(){return this.bottom-this.top};g.clone=function(){return new U(this.top,this.right,this.bottom,this.left)};g.contains=function(a){return this&&a?a instanceof U?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
g.expand=function(a,b,c,d){ha(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};g.translate=function(a,b){a instanceof K?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,t(b)&&(this.top+=b,this.bottom+=b));return this};
g.scale=function(a,b){var c=t(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function Nd(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}g=Nd.prototype;g.clone=function(){return new Nd(this.left,this.top,this.width,this.height)};g.intersects=function(a){return this.left<=a.left+a.width&&a.left<=this.left+this.width&&this.top<=a.top+a.height&&a.top<=this.top+this.height};
g.contains=function(a){return a instanceof K?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};g.distance=function(a){var b=a.x<this.left?this.left-a.x:Math.max(a.x-(this.left+this.width),0);a=a.y<this.top?this.top-a.y:Math.max(a.y-(this.top+this.height),0);return Math.sqrt(b*b+a*a)};g.getSize=function(){return new rb(this.width,this.height)};
g.getTopLeft=function(){return new K(this.left,this.top)};g.getCenter=function(){return new K(this.left+this.width/2,this.top+this.height/2)};g.getBottomRight=function(){return new K(this.left+this.width,this.top+this.height)};g.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};g.translate=function(a,b){a instanceof K?(this.left+=a.x,this.top+=a.y):(this.left+=a,t(b)&&(this.top+=b));return this};
g.scale=function(a,b){var c=t(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function V(a,b){var c=M(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function W(a,b){return V(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Od(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}B&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Pd(a){if(B&&!(8<=Number(J)))return a.offsetParent;var b=M(a),c=W(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(11==a.nodeType&&a.host&&(a=a.host),c=W(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Qd(a){for(var b=new U(0,Infinity,Infinity,0),c=L(a),d=c.v.body,e=c.v.documentElement,f=wb(c.v);a=Pd(a);)if(!(B&&0==a.clientWidth||G&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=W(a,"overflow")){var h=Rd(a),k=new K(a.clientLeft,a.clientTop);h.x+=k.x;h.y+=k.y;b.top=Math.max(b.top,h.y);b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(xb(c.v)||
window).document;c=yb(c)?c.documentElement:c.body;c=new rb(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}function Rd(a){var b=M(a),c=new K(0,0),d;d=b?M(b):document;d=!B||9<=Number(J)||yb(L(d).v)?d.documentElement:d.body;if(a==d)return c;a=Od(a);b=vb(L(b).v);c.x=a.left+b.x;c.y=a.top+b.y;return c}function Sd(a){"number"==typeof a&&(a+="px");return a}
function Td(a){var b=Ud;if("none"!=W(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function Ud(a){var b=a.offsetWidth,c=a.offsetHeight,d=G&&!b&&!c;return p(b)&&!d||!a.getBoundingClientRect?new rb(b,c):(a=Od(a),new rb(a.right-a.left,a.bottom-a.top))}var Vd=E?"MozUserSelect":G||D?"WebkitUserSelect":null;
function Wd(a){var b=a.getElementsByTagName("*");if(Vd){var c="none";a.style&&(a.style[Vd]=c);if(b){a=0;for(var d;d=b[a];a++)d.style&&(d.style[Vd]=c)}}else if(B||hb)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Xd(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e}
function Yd(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?Xd(a,c):0}var Zd={thin:2,medium:4,thick:6};function $d(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in Zd?Zd[c]:Xd(a,c)}
function ae(a){if(B&&!(9<=Number(J))){var b=$d(a,"borderLeft"),c=$d(a,"borderRight"),d=$d(a,"borderTop");a=$d(a,"borderBottom");return new U(d,c,a,b)}b=V(a,"borderLeftWidth");c=V(a,"borderRightWidth");d=V(a,"borderTopWidth");a=V(a,"borderBottomWidth");return new U(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function X(a,b,c,d,e){Kd.call(this,b,c,d,e);this.element=a}x(X,Kd);X.prototype.Sa=da;X.prototype.mb=function(){this.Sa();X.o.mb.call(this)};X.prototype.$=function(){this.Sa();X.o.$.call(this)};X.prototype.U=function(){this.Sa();X.o.U.call(this)};function Y(a,b,c,d,e){t(b)&&(b=[b]);t(c)&&(c=[c]);X.call(this,a,b,c,d,e);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");this.Ha=be}x(Y,X);var ce=1/1024,be=-1;
Y.prototype.Sa=function(){var a=this.coords[0];if(Math.abs(a-this.Ha)>=ce){var b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity\x3d"+100*Number(a)+")");this.Ha=a}};Y.prototype.U=function(){this.Ha=be;Y.o.U.call(this)};Y.prototype.$=function(){this.Ha=be;Y.o.$.call(this)};Y.prototype.show=function(){this.element.style.display=""};function de(a,b,c){Y.call(this,a,1,0,b,c)}x(de,Y);de.prototype.U=function(){this.show();de.o.U.call(this)};
de.prototype.$=function(){this.element.style.display="none";de.o.$.call(this)};function ee(a,b,c){Y.call(this,a,0,1,b,c)}x(ee,Y);ee.prototype.U=function(){this.show();ee.o.U.call(this)};function fe(a,b){return(b&8&&"rtl"==W(a,"direction")?b^4:b)&-9};function Z(){}Z.cb=void 0;Z.zb=function(){return Z.cb?Z.cb:Z.cb=new Z};Z.prototype.Kb=0;function ge(a,b,c,d){T.call(this);this.ob=a||document.body;this.N=L(this.ob);this.Jc=!a;this.b=null;this.K="";this.j=[];this.ga=[];this.$b=this.Ca=-1;this.R=!1;this.className="ac-renderer";this.qb="ac-row";this.Ib="active";this.ub="ac-active";this.yc="ac-highlighted";this.ia=b||null;this.Qc=null!=d?d:!0;this.Bc=!0;this.Ba=!1;this.Kc=!!c;this.Ra=!1;this.Ia=0;this.Zb=!1}x(ge,T);g=ge.prototype;g.nc=0;g.getElement=function(){return this.b};
g.pb=function(a,b,c){this.K=b;this.j=a;this.Ca=-1;this.$b=w();this.w=c;this.ga=[];he(this)};g.S=function(){this.R&&(this.R=!1,ie(this,!1),0<this.Ia?(Mb(this.ha),this.ha=new de(this.b,this.Ia),this.ha.play()):this.b.style.display="none")};g.show=function(){this.R||(this.R=!0,ie(this,!0),0<this.Ia?(Mb(this.ha),this.ha=new ee(this.b,this.Ia),this.ha.play()):this.b.style.display="")};
function ie(a,b){a.w&&(cd(a.w,"haspopup",b),cd(a.b,"expanded",b),cd(a.w,"expanded",b),b?cd(a.w,"owns",a.b.id):(a.w.removeAttribute("aria-owns"),dd(a.w,null)))}
function je(a,b){var c=0<=b&&b<a.j.length?a.j[b]:void 0,d=0<=b&&b<a.ga.length?a.ga[b]:void 0;if(a.dispatchEvent({type:"rowhilite",Uc:d,row:c?c.data:null})&&(0<=a.Ca&&Jb(a.ga[a.Ca],[a.ub,a.Ib]),a.Ca=b,d)){Hb(d,[a.ub,a.Ib]);a.w&&dd(a.w,d);var c=a.b||wb(document),e;e=c||wb(document);var f=Rd(d),h=Rd(e),k=ae(e);if(e==wb(document)){var l=f.x-e.scrollLeft,f=f.y-e.scrollTop;!B||10<=Number(J)||(l+=k.left,f+=k.top)}else l=f.x-h.x-k.left,f=f.y-h.y-k.top;var d=Ud(d),k=e.clientHeight-d.height,h=e.scrollLeft,
u=e.scrollTop,h=h+Math.min(l,Math.max(l-(e.clientWidth-d.width),0)),u=u+Math.min(f,Math.max(f-k,0));e=new K(h,u);c.scrollLeft=e.x;c.scrollTop=e.y}}g.T=function(a){if(-1==a)je(this,-1);else for(var b=0;b<this.j.length;b++)if(this.j[b].id==a){je(this,b);break}};
function ke(a){if(!a.b){var b=a.N.xb("DIV",{style:"display:none"});a.Zb&&(b.style.overflowY="auto");a.b=b;Hb(b,oa(a.className).split(" "));bd(b,"listbox");b.id=":"+(Z.zb().Kb++).toString(36);a.N.appendChild(a.ob,b);R(b,"click",a.Ab,!1,a);R(b,"mousedown",a.Bb,!1,a);R(b,"mouseover",a.Cb,!1,a)}}
function he(a){ke(a);a.Ra&&(a.b.style.visibility="hidden");a.gc&&(a.b.style.minWidth=a.gc.clientWidth-a.nc+"px");a.ga.length=0;a.N.Ic(a.b);if(a.ia&&a.ia.render)a.ia.render(a,a.b,a.j,a.K);else{var b=null;y(a.j,function(a){var d=a;a=this.K;var e=this.N.xb("DIV",{className:this.qb,id:":"+(Z.zb().Kb++).toString(36)});bd(e,"option");if(this.ia&&this.ia.Wb)this.ia.Wb(d,a,e);else if(d=d.data.toString(),"textContent"in e)e.textContent=d;else if(3==e.nodeType)e.data=d;else if(e.firstChild&&3==e.firstChild.nodeType){for(;e.lastChild!=
e.firstChild;)e.removeChild(e.lastChild);e.firstChild.data=d}else Bb(e),e.appendChild(M(e).createTextNode(String(d)));a&&this.Qc&&(this.fc=!1,le(this,e,a));Gb(e,this.qb);this.ga.push(e);a=e;this.Ra?this.b.insertBefore(a,b):this.N.appendChild(this.b,a);b=a},a)}0==a.j.length?a.S():(a.show(),me(a),Wd(a.b))}
function me(a){if(a.w&&a.Jc){var b=a.kc||a.w,c,d=a.Kc?5:1;a.Ra&&(d^=1);c=d;var e=65;a.Zb&&(a.b.style.height="",e|=32);var d=a.b,f=c^1,h,k;if(h=d.offsetParent){var l="HTML"==h.tagName||"BODY"==h.tagName;l&&"static"==W(h,"position")||(k=Rd(h),l||(l=(l="rtl"==W(h,"direction"))&&E?-h.scrollLeft:!l||ib&&I("8")||"visible"==W(h,"overflowX")?h.scrollLeft:h.scrollWidth-h.clientWidth-h.scrollLeft,k=qb(k,new K(l,h.scrollTop))))}h=k||new K;k=Rd(b);l=Td(b);k=new Nd(k.x,k.y,l.width,l.height);if(l=Qd(b)){var u=
new Nd(l.left,l.top,l.right-l.left,l.bottom-l.top),l=Math.max(k.left,u.left),C=Math.min(k.left+k.width,u.left+u.width);if(l<=C){var Q=Math.max(k.top,u.top),u=Math.min(k.top+k.height,u.top+u.height);Q<=u&&(k.left=l,k.top=Q,k.width=C-l,k.height=u-Q)}}l=L(b);Q=L(d);if(l.v!=Q.v){C=l.v.body;var Q=xb(Q.v),u=new K(0,0),F;F=(F=M(C))?xb(F):window;if(eb(F,"parent")){var Sb=C;do{var ca;F==Q?ca=Rd(Sb):(ca=Od(Sb),ca=new K(ca.left,ca.top));u.x+=ca.x;u.y+=ca.y}while(F&&F!=Q&&F!=F.parent&&(Sb=F.frameElement)&&(F=
F.parent))}C=qb(u,Rd(C));!B||9<=Number(J)||yb(l.v)||(C=qb(C,vb(l.v)));k.left+=C.x;k.top+=C.y}b=fe(b,c);c=k.left;b&4?c+=k.width:b&2&&(c+=k.width/2);var b=new K(c,k.top+(b&1?k.height:0)),b=qb(b,h),m;e&&(m=Qd(d))&&(m.top-=h.y,m.right-=h.x,m.bottom-=h.y,m.left-=h.x);b=b.clone();h=fe(d,f);f=Td(d);c=f.clone();b=b.clone();c=c.clone();k=0;0!=h&&(h&4?b.x-=c.width+0:h&2&&(b.x-=c.width/2),h&1&&(b.y-=c.height+0));e&&(m?(h=b,k=c,l=0,65==(e&65)&&(h.x<m.left||h.x>=m.right)&&(e&=-2),132==(e&132)&&(h.y<m.top||h.y>=
m.bottom)&&(e&=-5),h.x<m.left&&e&1&&(h.x=m.left,l|=1),e&16&&(C=h.x,h.x<m.left&&(h.x=m.left,l|=4),h.x+k.width>m.right&&(k.width=Math.min(m.right-h.x,C+k.width-m.left),k.width=Math.max(k.width,0),l|=4)),h.x+k.width>m.right&&e&1&&(h.x=Math.max(m.right-k.width,m.left),l|=1),e&2&&(l|=(h.x<m.left?16:0)|(h.x+k.width>m.right?32:0)),h.y<m.top&&e&4&&(h.y=m.top,l|=2),e&32&&(C=h.y,h.y<m.top&&(h.y=m.top,l|=8),h.y+k.height>m.bottom&&(k.height=Math.min(m.bottom-h.y,C+k.height-m.top),k.height=Math.max(k.height,0),
l|=8)),h.y+k.height>m.bottom&&e&4&&(h.y=Math.max(m.bottom-k.height,m.top),l|=2),e&8&&(l|=(h.y<m.top?64:0)|(h.y+k.height>m.bottom?128:0)),e=l):e=256,k=e);e=new Nd(0,0,0,0);e.left=b.x;e.top=b.y;e.width=c.width;e.height=c.height;k&496||(b=e.getTopLeft(),b instanceof K?(m=b.x,b=b.y):(m=b,b=void 0),d.style.left=Sd(m),d.style.top=Sd(b),c=e.getSize(),f==c||f&&c&&f.width==c.width&&f.height==c.height||(e=c,m=yb(L(M(d)).v),!B||I("10")||m&&I("8")?(d=d.style,E?d.MozBoxSizing="border-box":G?d.WebkitBoxSizing=
"border-box":d.boxSizing="border-box",d.width=Math.max(e.width,0)+"px",d.height=Math.max(e.height,0)+"px"):(f=d.style,m?(B?(m=Yd(d,"paddingLeft"),b=Yd(d,"paddingRight"),c=Yd(d,"paddingTop"),h=Yd(d,"paddingBottom"),m=new U(c,b,h,m)):(m=V(d,"paddingLeft"),b=V(d,"paddingRight"),c=V(d,"paddingTop"),h=V(d,"paddingBottom"),m=new U(parseFloat(c),parseFloat(b),parseFloat(h),parseFloat(m))),d=ae(d),f.pixelWidth=e.width-d.left-m.left-m.right-d.right,f.pixelHeight=e.height-d.top-m.top-m.bottom-d.bottom):(f.pixelWidth=
e.width,f.pixelHeight=e.height))));a.Ra&&(a.b.style.visibility="visible")}}g.getTarget=function(){return this.w||null};g.l=function(){this.b&&(hc(this.b,"click",this.Ab,!1,this),hc(this.b,"mousedown",this.Bb,!1,this),hc(this.b,"mouseover",this.Cb,!1,this),this.N.removeNode(this.b),this.b=null,this.R=!1);Mb(this.ha);this.ob=null;ge.o.l.call(this)};
function le(a,b,c){if(a.Ba||!a.fc)if(3==b.nodeType){var d=null;q(c)&&1<c.length&&!a.Ba&&(d=Ha(c,1));c=ne(a,c);if(0!=c.length){var e=b.nodeValue,f=a.Bc?new RegExp("\\b(?:"+c+")","gi"):new RegExp(c,"gi");c=[];for(var h=0,k=f.exec(e),l=0;k;)l++,c.push(e.substring(h,k.index)),c.push(e.substring(k.index,f.lastIndex)),h=f.lastIndex,k=f.exec(e);c.push(e.substring(h));if(1<c.length){d=a.Ba?l:1;for(e=0;e<d;e++)f=2*e,b.nodeValue=c[f],h=a.N.createElement("B"),h.className=a.yc,a.N.appendChild(h,a.N.createTextNode(c[f+
1])),h=b.parentNode.insertBefore(h,b.nextSibling),b.parentNode.insertBefore(a.N.createTextNode(""),h.nextSibling),b=h.nextSibling;b.nodeValue=Ha(c,2*d).join("");a.fc=!0}else d&&le(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,le(a,b,c),b=d}
function ne(a,b){var c="";if(!b)return c;q(b)&&(b=Aa(b,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));a.Ba?q(b)?c=Ba(b,xa).join("|"):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=xa(c),c=c.replace(/ /g,"|")):q(b)?c=0<b.length?xa(b[0]):"":/^\W/.test(b)||(c=xa(b));return c}function oe(a,b){for(;b&&b!=a.b&&!Fb(b,a.qb);)b=b.parentNode;return b?za(a.ga,b):-1}g.Ab=function(a){var b=oe(this,a.target);0<=b&&this.dispatchEvent({type:Mc,row:this.j[b].id});a.stopPropagation()};
g.Bb=function(a){a.stopPropagation();a.preventDefault()};g.Cb=function(a){a=oe(this,a.target);0<=a&&!(300>w()-this.$b)&&this.dispatchEvent({type:Lc,row:this.j[a].id})};function pe(a,b,c,d){this.Ka=null;d&&(this.Ka=new Za((location.hash||"").substr(1)));this.u=r(a)?document.getElementById(a):a;R(this.u,["focus","click"],function(){this.u.setSelectionRange(0,this.u.value.length)},!1,this);a=new ge(null,{Wb:function(a,b,c){b='\x3cspan class\x3d"name"\x3e';var d=a.data.name_suffix;b=d?b+(a.data.name+'\x3c/span\x3e\x3cspan class\x3d"suffix"\x3e'+d):b+a.data.display_name;b+="\x3c/span\x3e";(a=a.data.type)&&(b+='\x3cspan class\x3d"type"\x3e'+a+"\x3c/span\x3e");c.innerHTML=
b}});a.gc=this.u;this.Z=new qe(b,c,this.Ka,this.u);this.da=new ud(null,null,!1);wd(this.da);this.da.dc=!1;this.da.i=this;Kc.call(this,this.Z,a,this.da);this.Ya=!1;this.D("update",function(a){this.u.value=a.row?a.row.name:""},!1,this);this.enable(!0);if(this.Ka){var e=this.Ka.get("q");e&&r(e)&&setTimeout(v(function(){this.u.value=e.toString();this.da.update()},this),0)}}x(pe,Kc);
pe.prototype.enable=function(a){if(this.Ya!=a)if(this.Ya=a){a=this.da;var b=this.u;ha(b)&&1==b.nodeType&&(bd(b,"combobox"),cd(b,"autocomplete","list"));a.s.D(b,"focus",a.ab);a.s.D(b,"blur",a.$a);if(!a.c&&(a.ya.D(b,"keydown",a.Nb),ha(b)&&1==b.nodeType)){var c;a:{var d=M(b);try{c=d&&d.activeElement;break a}catch(e){}c=null}c==b&&zd(a,b)}}else c=this.da,a=this.u,ha(a)&&1==a.nodeType&&(a.removeAttribute("role"),a.removeAttribute("aria-autocomplete")),a==c.c&&c.$a(),c.s.F(a,"focus",c.ab),c.s.F(a,"blur",
c.$a),c.c||c.ya.F(a,"keydown",c.Nb)};pe.prototype.Hc=function(a,b){b&&R(this.I,"rowhilite",function(b){b.row&&a(b.row)},!1,this);R(this,"update",function(b){b.row&&a(b.row)},!1,this);var c=v(function(b){b.preventDefault();this.Ya&&this.search(this.u.value,1,v(function(b,c){var d=c[0];d&&a(d)},this))},this),d=Cb(this.u);d&&R(d,"submit",c);R(this.u,["webkitspeechchange","speechchange"],c)};pe.prototype.search=function(a,b,c){Bd(this.Z,a,b,c)};ba("kt.OsmNamesAutocomplete",pe);
ba("kt.OsmNamesAutocomplete.prototype.registerCallback",pe.prototype.Hc);function qe(a,b,c,d){this.Pc=a||"https://search.osmnames.org/";this.Gb=b;this.la=c||null;this.u=d}
function Bd(a,b,c,d){a.u&&Ib(a.u,"working");a.Na&&b!=a.Lb&&(a.Na.abort(),a.Na=null);b&&1!=b.length?(1==c&&(a.Lb=b),1<c&&b===a.Lb||(a.la&&(a.la.set("q",b),location.hash=a.la.toString()),c=a.Pc,a.la&&a.la.get("country_code")&&(c+=a.la.get("country_code")+"/"),c+="q/"+encodeURIComponent(b)+".js",a.Gb&&(c+="?key\x3d"+a.Gb),a.u&&Gb(a.u,"working"),a.Na=Ac(c,v(function(a){this.u&&Ib(this.u,"working");a=a.target;Ic(a)&&(a=a.a?oc(a.a.responseText):void 0,a=a.results,y(a,function(a){if(a=a.boundingbox)180<
a[0]&&180<a[2]?(a[0]-=360,a[2]-=360):-180>a[0]&&-180>a[2]&&(a[0]+=360,a[2]+=360)},this),d(b,a),this.Na=null)},a)))):d(b,[])};})();
